language: python

python:
  - 2.7
  - 3.6
  - 3.7
  - nightly

env:
  - DJANGO='django>=1.8.0,<1.9.0'
  - DJANGO='django>=1.10.0,<1.11.0'
  - DJANGO='django>=1.11.0,<2.0'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'

before_install:
  - pip install coveralls

install:
  - pip install --upgrade poetry
  - poetry install -v
  - poetry run pip install $DJANGO

script:
  - DJANGO_SETTINGS_MODULE=tests.test_settings poetry run pytest --cov=sweetify tests/

after_success:
  - coveralls

matrix:
  exclude:
    - python: 2.7
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
